proj4_final-components/QEDMainPage/config/routes.rb
Blog::Application.routes.draw do

	resources :posts do
   get :seeall, on: :collection
	end

  match ':controller(/:action(/:id))(.:format)'
end

proj4_final-components/QEDMainPage/app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :attachment, :comments, :content, :displayname, :role, :title, :user

  validates :title, :content, :presence => true
  validates :title, :length => { :minimum => 2 }
  validates :title, :uniqueness => true
end

proj4_final-components/QEDMainPage/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

proj4_final-components/QEDMainPage/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def seeall
		@posts = Post.order('created_at DESC')
	end

	
	def index
		@posts = Post.order('created_at DESC')
	end	

	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(params[:post])
		if @post.save
			redirect_to posts_path, :notice => "Your post was saved"
		else
			render "new"
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update_attributes(params[:post])
			redirect_to posts_path, :notice => "Your post has been updated"
		else
			render "edit"
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path, :notice => "Your post has been deleted"
	end

end

proj4_final-components/QEDMainPage/app/helpers/application_helper.rb
module ApplicationHelper
end

proj4_final-components/QEDMainPage/app/helpers/posts_helper.rb
module PostsHelper
end

proj4_final-components/QEDMainPage/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>QED</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
	<p><%= value %></p>
<% end %>

<div id="page"> 
    <div id="header">
    	<div class="title">QED</div>
        <div class="subText">Problem Solved. </div>
    </div>
    <div id="bar">

    </div>
    
    
    <div id="pageContent">
    



<%= yield %>
</div>

<div id="footer"><a href="http://www.aszx.net">web development</a> by <a href="http://www.bryantsmith.com">bryant smith</a></div>

</body>
</html>

proj4_final-components/QEDMainPage/app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<h2> Errors:</h2>
		<ul>
			<% @post.errors.full_messages.each do |message| %>
					<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>
	<p>
		<%= f.label :title %><br />
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :content %><br />
		<%= f.text_area :content %>
	</p>
	<p>
		<%= f.submit "Update Post" %>
	</p>
<% end %>

proj4_final-components/QEDMainPage/app/views/posts/index.html.erb
<% @posts.each do |post| %>
<% if post.created_at >= 1.week.ago %>
	<% if post.role == 1 %>
			<h2>Announcement: <%= link_to post.title, post %></h2>
	<% end %>
	<% if post.role == 0 %>
		<h2><%= link_to post.title, post %></h2>
	<% end %>
	<h2><%= link_to post.title, post %></h2>

	
	<p><%= truncate post.content%></p>

	
	<small><%= time_ago_in_words post.created_at %> ago, by <%= post.displayname %></small>


<% end %>
<% end %>
<p><%= link_to "See More", seeall_posts_path %></p>


<p><%= link_to "Add a New Post", new_post_path %></p>

proj4_final-components/QEDMainPage/app/views/posts/new.html.erb
<h2>Add a New Post</h2>

<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<h2> Errors:</h2>
		<ul>
			<% @post.errors.full_messages.each do |message| %>
					<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>
	<p>
		<%= f.label :title %><br />
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :content %><br />
		<%= f.text_area :content %>
		
	</p>
	<p>
		<%= f.submit "Add New Post" %>
	</p>

<% end %>

proj4_final-components/QEDMainPage/app/views/posts/seeall.html.erb
<% @posts.each do |post| %>
	<% if post.role == 1 %>
			<h2>Announcement: <%= link_to post.title, post %></h2>
	<% end %>
	<% if post.role == 0 %>
		<h2><%= link_to post.title, post %></h2>
	<% end %>
	<h2><%= link_to post.title, post %></h2>
	<p><%= truncate post.content%></p>
	<small>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <%= time_ago_in_words post.created_at %> ago, by <%= post.displayname %></small>

<% end %>



<p><%= link_to "Add a New Post", new_post_path %></p>

proj4_final-components/QEDMainPage/app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
	<% content = (@post.content).split("<latex>") %>
	
	<% if @post.content.starts_with?("<latex>") %>
	
		<% i = 0 %>
		
		<% while (i < content.length) do %>
			<%# image_tag Tex2png.new_image(content[i]) %>
			<%= image_tag "http://www.khwiki.net/images/thumb/4/4a/King_Mickey_KHREC.png/337px-King_Mickey_KHREC.png" %>
			<% if (i != ((content.length)-1)) %>
			<p> <%=content[i+1] %></p>
			<% end %>
			<% i = i+2 %>
		<% end %>
		
	<% else %>
		<p><%= content[0] %> </p>
		<% i = 1 %>
		<% while (i < content.length) do %>
			<%# image_tag Tex2png.new_image(content[i]) %>
			<%= image_tag "http://www.khwiki.net/images/thumb/4/4a/King_Mickey_KHREC.png/337px-King_Mickey_KHREC.png" %>
			<% if (i != ((content.length)-1)) %>
			<p> <%=content[i+1] %></p>
			<% end %>
			
			<% i = i+2 %>
		<% end %>
	<% end %>


<br></br>

<small><%= link_to "Edit", edit_post_path(@post)%><small>
<small><%= @post.created_at %></small>